<?php

declare(strict_types=1);

namespace CoenJacobs\Mozart\Tests\Unit\Autoload;

use CoenJacobs\Mozart\Autoload\AutoloaderFileWriter;
use CoenJacobs\Mozart\Autoload\AutoloaderGenerator;
use CoenJacobs\Mozart\Config\Mozart;
use CoenJacobs\Mozart\Exceptions\FileOperationException;
use CoenJacobs\Mozart\FilesHandler;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;

class AutoloaderGeneratorTest extends TestCase
{
    protected string $testsWorkingDir;
    protected Mozart $config;

    public function setUp(): void
    {
        parent::setUp();

        $this->testsWorkingDir = sys_get_temp_dir() . '/mozart_autoloader_test_' . uniqid();
        mkdir($this->testsWorkingDir, 0777, true);

        $configArgs = [
            'dep_namespace' => 'MyPlugin\\Dependencies',
            'dep_directory' => '/src/dependencies/',
            'classmap_directory' => '/classes/',
            'classmap_prefix' => 'MyPlugin_',
        ];

        $mozart = new Mozart();
        $this->config = $mozart->loadFromString(json_encode($configArgs));
        $this->config->setWorkingDir($this->testsWorkingDir);

        // Create output directories
        mkdir($this->testsWorkingDir . '/src/dependencies', 0777, true);
        mkdir($this->testsWorkingDir . '/classes', 0777, true);
    }

    #[Test]
    public function it_produces_unique_hash_from_namespace(): void
    {
        $generator = new AutoloaderGenerator($this->config);

        $expected = md5('MyPlugin\\Dependencies\\');
        $this->assertEquals($expected, $generator->getHash());
    }

    #[Test]
    public function it_generates_entry_point_autoload_php(): void
    {
        $this->setUpVendorComposer();

        $generator = new AutoloaderGenerator($this->config);
        $generator->generate([]);

        $autoloadFile = $this->testsWorkingDir . '/src/dependencies/autoload.php';
        $this->assertFileExists($autoloadFile);

        $content = file_get_contents($autoloadFile);
        $hash = $generator->getHash();

        $this->assertStringContainsString('@generated by Mozart', $content);
        $this->assertStringContainsString("MozartAutoloaderInit{$hash}::getLoader()", $content);
        $this->assertStringContainsString("require_once __DIR__ . '/composer/autoload_real.php'", $content);
    }

    #[Test]
    public function it_generates_psr4_mapping(): void
    {
        $this->setUpVendorComposer();

        $generator = new AutoloaderGenerator($this->config);
        $generator->generate([]);

        $psr4File = $this->testsWorkingDir . '/src/dependencies/composer/autoload_psr4.php';
        $this->assertFileExists($psr4File);

        $content = file_get_contents($psr4File);
        $this->assertStringContainsString('MyPlugin\\\\Dependencies\\\\', $content);
    }

    #[Test]
    public function it_generates_classmap_from_scanned_files(): void
    {
        // Create a PHP class file in the dep directory
        $classDir = $this->testsWorkingDir . '/src/dependencies/Psr/Container';
        mkdir($classDir, 0777, true);
        file_put_contents(
            $classDir . '/ContainerInterface.php',
            "<?php\nnamespace MyPlugin\\Dependencies\\Psr\\Container;\ninterface ContainerInterface {}\n"
        );

        $this->setUpVendorComposer();

        $generator = new AutoloaderGenerator($this->config);
        $generator->generate([]);

        $classmapFile = $this->testsWorkingDir . '/src/dependencies/composer/autoload_classmap.php';
        $this->assertFileExists($classmapFile);

        $content = file_get_contents($classmapFile);
        $this->assertStringContainsString(
            'MyPlugin\\\\Dependencies\\\\Psr\\\\Container\\\\ContainerInterface',
            $content
        );
    }

    #[Test]
    public function it_generates_classmap_from_classmap_directory(): void
    {
        // Create a prefixed global-scope class in classmap directory
        $classmapPackageDir = $this->testsWorkingDir . '/classes/mustangostang/spyc';
        mkdir($classmapPackageDir, 0777, true);
        file_put_contents(
            $classmapPackageDir . '/Spyc.php',
            "<?php\nclass MyPlugin_Spyc {}\n"
        );

        $this->setUpVendorComposer();

        $generator = new AutoloaderGenerator($this->config);
        $generator->generate([]);

        $classmapFile = $this->testsWorkingDir . '/src/dependencies/composer/autoload_classmap.php';
        $content = file_get_contents($classmapFile);
        $this->assertStringContainsString('MyPlugin_Spyc', $content);
    }

    #[Test]
    public function it_generates_files_entries_from_tracked_targets(): void
    {
        $this->setUpVendorComposer();

        $targets = [
            'classes/mustangostang/spyc/Spyc.php',
        ];

        $generator = new AutoloaderGenerator($this->config);
        $generator->generate($targets);

        $filesFile = $this->testsWorkingDir . '/src/dependencies/composer/autoload_files.php';
        $this->assertFileExists($filesFile);

        $content = file_get_contents($filesFile);
        $this->assertStringContainsString('Spyc.php', $content);
    }

    #[Test]
    public function it_skips_files_autoloader_when_no_entries_exist(): void
    {
        $this->setUpVendorComposer();

        $generator = new AutoloaderGenerator($this->config);
        $generator->generate([]);

        $filesFile = $this->testsWorkingDir . '/src/dependencies/composer/autoload_files.php';
        $this->assertFileDoesNotExist($filesFile);
    }

    #[Test]
    public function it_generates_static_autoloader_arrays(): void
    {
        $this->setUpVendorComposer();

        $generator = new AutoloaderGenerator($this->config);
        $generator->generate([]);

        $staticFile = $this->testsWorkingDir . '/src/dependencies/composer/autoload_static.php';
        $this->assertFileExists($staticFile);

        $content = file_get_contents($staticFile);
        $hash = $generator->getHash();

        $this->assertStringContainsString("MozartStaticInit{$hash}", $content);
        $this->assertStringContainsString('$prefixLengthsPsr4', $content);
        $this->assertStringContainsString('$prefixDirsPsr4', $content);
        $this->assertStringContainsString('$classMap', $content);
        $this->assertStringContainsString('getInitializer', $content);
    }

    #[Test]
    public function it_generates_autoload_real_with_unique_class(): void
    {
        $this->setUpVendorComposer();

        $generator = new AutoloaderGenerator($this->config);
        $generator->generate([]);

        $realFile = $this->testsWorkingDir . '/src/dependencies/composer/autoload_real.php';
        $this->assertFileExists($realFile);

        $content = file_get_contents($realFile);
        $hash = $generator->getHash();

        $this->assertStringContainsString("class MozartAutoloaderInit{$hash}", $content);
        $this->assertStringContainsString('loadClassLoader', $content);
        $this->assertStringContainsString('getLoader', $content);
        $this->assertStringContainsString('spl_autoload_register', $content);
    }

    #[Test]
    public function it_copies_class_loader_from_vendor(): void
    {
        $this->setUpVendorComposer();

        $generator = new AutoloaderGenerator($this->config);
        $generator->generate([]);

        $classLoaderFile = $this->testsWorkingDir . '/src/dependencies/composer/ClassLoader.php';
        $this->assertFileExists($classLoaderFile);

        $content = file_get_contents($classLoaderFile);
        $this->assertStringContainsString('Composer\Autoload', $content);
        $this->assertStringContainsString('class ClassLoader', $content);
    }

    #[Test]
    public function it_cleans_previous_autoloader_on_re_run(): void
    {
        $this->setUpVendorComposer();

        $generator = new AutoloaderGenerator($this->config);

        // First run
        $generator->generate([]);
        $this->assertFileExists(
            $this->testsWorkingDir . '/src/dependencies/autoload.php'
        );

        // Create a stale file in the composer directory
        file_put_contents(
            $this->testsWorkingDir . '/src/dependencies/composer/stale_file.php',
            '<?php // stale'
        );

        // Second run should clean the directory
        $generator->generate([]);

        $this->assertFileDoesNotExist(
            $this->testsWorkingDir . '/src/dependencies/composer/stale_file.php'
        );
        $this->assertFileExists(
            $this->testsWorkingDir . '/src/dependencies/autoload.php'
        );
    }

    #[Test]
    public function it_throws_when_class_loader_is_missing(): void
    {
        // Do NOT set up vendor/composer/ClassLoader.php
        $this->expectException(FileOperationException::class);
        $this->expectExceptionMessage('ClassLoader.php');

        $generator = new AutoloaderGenerator($this->config);
        $generator->generate([]);
    }

    #[Test]
    public function it_includes_files_block_in_autoload_real_when_files_exist(): void
    {
        $this->setUpVendorComposer();

        $targets = ['classes/somefile.php'];

        $generator = new AutoloaderGenerator($this->config);
        $generator->generate($targets);

        $realFile = $this->testsWorkingDir . '/src/dependencies/composer/autoload_real.php';
        $content = file_get_contents($realFile);

        $this->assertStringContainsString('__composer_autoload_files', $content);
        $this->assertStringContainsString('$filesToLoad', $content);
    }

    #[Test]
    public function it_omits_files_block_in_autoload_real_when_no_files(): void
    {
        $this->setUpVendorComposer();

        $generator = new AutoloaderGenerator($this->config);
        $generator->generate([]);

        $realFile = $this->testsWorkingDir . '/src/dependencies/composer/autoload_real.php';
        $content = file_get_contents($realFile);

        $this->assertStringNotContainsString('__composer_autoload_files', $content);
        $this->assertStringNotContainsString('$filesToLoad', $content);
    }

    #[Test]
    public function it_computes_relative_paths_correctly(): void
    {
        $filesHandler = new FilesHandler($this->config);
        $writer = new AutoloaderFileWriter($filesHandler, $this->config->getDepDirectory(), 'testhash');

        $this->assertEquals(
            '../file.php',
            $writer->computeRelativePath('src/dependencies/composer', 'src/dependencies/file.php')
        );

        $this->assertEquals(
            '../../../classes/pkg/File.php',
            $writer->computeRelativePath('src/dependencies/composer', 'classes/pkg/File.php')
        );
    }

    /**
     * Set up a minimal vendor/composer/ directory with ClassLoader.php and LICENSE.
     */
    protected function setUpVendorComposer(): void
    {
        $vendorComposerDir = $this->testsWorkingDir . '/vendor/composer';
        mkdir($vendorComposerDir, 0777, true);

        // Copy real ClassLoader.php from the actual project vendor
        $realClassLoader = dirname(__DIR__, 3) . '/vendor/composer/ClassLoader.php';
        if (file_exists($realClassLoader)) {
            copy($realClassLoader, $vendorComposerDir . '/ClassLoader.php');
        } else {
            // Fallback: create a minimal stub
            file_put_contents(
                $vendorComposerDir . '/ClassLoader.php',
                "<?php\nnamespace Composer\\Autoload;\nclass ClassLoader {\n"
                . "    public function __construct(\$vendorDir = '') {}\n}\n"
            );
        }

        file_put_contents($vendorComposerDir . '/LICENSE', 'MIT License');
    }

    public function tearDown(): void
    {
        parent::tearDown();

        if (is_dir($this->testsWorkingDir)) {
            $this->removeDirectory($this->testsWorkingDir);
        }
    }

    /**
     * Recursively remove a directory and its contents.
     */
    protected function removeDirectory(string $dir): void
    {
        if (!is_dir($dir)) {
            return;
        }

        $it = new RecursiveDirectoryIterator($dir, RecursiveDirectoryIterator::SKIP_DOTS);
        $files = new RecursiveIteratorIterator(
            $it,
            RecursiveIteratorIterator::CHILD_FIRST
        );

        foreach ($files as $file) {
            if ($file->isDir()) {
                rmdir($file->getRealPath());
            } else {
                unlink($file->getRealPath());
            }
        }

        rmdir($dir);
    }
}
