<?php

namespace CoenJacobs\Mozart\Autoload;

use CoenJacobs\Mozart\Config\Mozart;
use CoenJacobs\Mozart\Exceptions\FileOperationException;
use CoenJacobs\Mozart\FilesHandler;
use Composer\ClassMapGenerator\ClassMapGenerator;

/**
 * Generates a Composer-compatible autoloader for prefixed dependencies.
 *
 * @SuppressWarnings(PHPMD.TooManyMethods)
 * @SuppressWarnings(PHPMD.ExcessiveClassComplexity)
 */
class AutoloaderGenerator
{
    protected Mozart $config;
    protected FilesHandler $files;
    protected string $hash;

    /** @var array<string, array<string>> PSR-4 prefix → directories */
    protected array $psr4Entries = [];

    /** @var array<string, string> FQCN → file path */
    protected array $classmapEntries = [];

    /** @var array<string, string> hash → file path */
    protected array $filesEntries = [];

    public function __construct(Mozart $config, ?FilesHandler $filesHandler = null)
    {
        $this->config = $config;
        $this->files = $filesHandler ?? new FilesHandler($config);
        $this->hash = $this->generateHash();
    }

    /**
     * Generate the complete autoloader for prefixed dependencies.
     *
     * @param array<string> $fileTargets Target paths of files that need eager loading
     */
    public function generate(array $fileTargets): void
    {
        $this->cleanPreviousAutoloader();

        $this->buildPsr4Entries();
        $this->buildClassmapEntries();
        $this->buildFilesEntries($fileTargets);

        $composerDir = $this->config->getDepDirectory() . 'composer';
        $this->files->createDirectory($composerDir);

        $this->writeAutoloadPhp();
        $this->writeAutoloadReal();
        $this->writeAutoloadStatic();
        $this->writeAutoloadClassmap();
        $this->writeAutoloadPsr4();

        if (!empty($this->filesEntries)) {
            $this->writeAutoloadFiles();
        }

        $this->copyClassLoader();
        $this->copyLicense();
    }

    /**
     * Build the PSR-4 entries mapping the dependency namespace to dep_directory.
     */
    protected function buildPsr4Entries(): void
    {
        $namespace = $this->config->getDependencyNamespace();
        $depDir = rtrim($this->config->getDepDirectory(), DIRECTORY_SEPARATOR . '/');

        $this->psr4Entries[$namespace] = [$depDir];
    }

    /**
     * Build classmap entries by scanning both output directories.
     *
     * @SuppressWarnings(PHPMD.StaticAccess)
     */
    protected function buildClassmapEntries(): void
    {
        $workingDir = $this->config->getWorkingDir();
        $depDir = $workingDir . $this->config->getDepDirectory();
        $cmapDir = $workingDir . $this->config->getClassmapDirectory();

        $classmap = [];

        if (is_dir($depDir)) {
            $classmap = array_merge($classmap, ClassMapGenerator::createMap($depDir));
        }

        if (is_dir($cmapDir) && realpath($cmapDir) !== realpath($depDir)) {
            $classmap = array_merge($classmap, ClassMapGenerator::createMap($cmapDir));
        }

        // Convert absolute paths to paths relative to working directory
        foreach ($classmap as $class => $absolutePath) {
            $relativePath = str_replace($workingDir, '', $absolutePath);
            $relativePath = str_replace(DIRECTORY_SEPARATOR, '/', $relativePath);
            $this->classmapEntries[$class] = $relativePath;
        }
    }

    /**
     * Build files entries from tracked autoloader targets.
     *
     * @param array<string> $targets Target file paths relative to working directory
     */
    protected function buildFilesEntries(array $targets): void
    {
        foreach ($targets as $target) {
            $identifier = md5($target);
            $normalizedPath = str_replace(DIRECTORY_SEPARATOR, '/', $target);
            $this->filesEntries[$identifier] = $normalizedPath;
        }
    }

    /**
     * Generate a unique hash based on the dependency namespace.
     */
    public function generateHash(): string
    {
        return md5($this->config->getDependencyNamespace());
    }

    /**
     * Remove previously generated autoloader files.
     */
    protected function cleanPreviousAutoloader(): void
    {
        $composerDir = $this->config->getDepDirectory() . 'composer';
        if (is_dir($this->config->getWorkingDir() . $composerDir)) {
            $this->files->deleteDirectory($composerDir);
        }

        $autoloadFile = $this->config->getDepDirectory() . 'autoload.php';
        $absolutePath = $this->config->getWorkingDir() . $autoloadFile;
        if (file_exists($absolutePath)) {
            unlink($absolutePath);
        }
    }

    /**
     * Write the autoload.php entry point.
     */
    protected function writeAutoloadPhp(): void
    {
        $content = <<<PHP
<?php

// autoload.php @generated by Mozart

require_once __DIR__ . '/composer/autoload_real.php';

return MozartAutoloaderInit{$this->hash}::getLoader();

PHP;

        $this->files->writeFile(
            $this->config->getDepDirectory() . 'autoload.php',
            $content
        );
    }

    /**
     * Write the autoload_real.php bootstrap file.
     */
    protected function writeAutoloadReal(): void
    {
        $hash = $this->hash;
        $filesBlock = '';

        if (!empty($this->filesEntries)) {
            $filesBlock = <<<'FILESBLOCK'

        $filesToLoad = \Composer\Autoload\MozartStaticInit{HASH}::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }
FILESBLOCK;
            $filesBlock = str_replace('{HASH}', $hash, $filesBlock);
        }

        $content = <<<PHP
<?php

// autoload_real.php @generated by Mozart

class MozartAutoloaderInit{$hash}
{
    private static \$loader;

    public static function loadClassLoader(\$class)
    {
        if ('Composer\\Autoload\\ClassLoader' === \$class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \\Composer\\Autoload\\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::\$loader) {
            return self::\$loader;
        }

        spl_autoload_register(array('MozartAutoloaderInit{$hash}', 'loadClassLoader'), true, true);
        self::\$loader = \$loader = new \\Composer\\Autoload\\ClassLoader(\\dirname(__DIR__));
        spl_autoload_unregister(array('MozartAutoloaderInit{$hash}', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\\Composer\\Autoload\\MozartStaticInit{$hash}::getInitializer(\$loader));

        \$loader->register(true);
{$filesBlock}

        return \$loader;
    }
}

PHP;

        $this->files->writeFile(
            $this->config->getDepDirectory() . 'composer/autoload_real.php',
            $content
        );
    }

    /**
     * Write the autoload_static.php file with static arrays for OPcache.
     */
    protected function writeAutoloadStatic(): void
    {
        $hash = $this->hash;
        $depDir = rtrim($this->config->getDepDirectory(), DIRECTORY_SEPARATOR . '/');

        // Build files array
        $filesArray = '';
        if (!empty($this->filesEntries)) {
            $filesArray = $this->renderStaticFilesArray($depDir);
        }

        // Build PSR-4 arrays
        $prefixLengths = $this->renderStaticPrefixLengths();
        $prefixDirs = $this->renderStaticPrefixDirs($depDir);

        // Build classmap array
        $classmapArray = $this->renderStaticClassmap($depDir);

        $content = <<<PHP
<?php

// autoload_static.php @generated by Mozart

namespace Composer\Autoload;

class MozartStaticInit{$hash}
{
{$filesArray}{$prefixLengths}{$prefixDirs}{$classmapArray}
    public static function getInitializer(ClassLoader \$loader)
    {
        return \\Closure::bind(function () use (\$loader) {
{$this->renderStaticInitializer()}
        }, null, ClassLoader::class);
    }
}

PHP;

        $this->files->writeFile(
            $this->config->getDepDirectory() . 'composer/autoload_static.php',
            $content
        );
    }

    /**
     * Write the autoload_classmap.php file.
     */
    protected function writeAutoloadClassmap(): void
    {
        $entries = '';
        foreach ($this->classmapEntries as $class => $path) {
            $escapedClass = addslashes($class);
            $relativePath = $this->computeRelativePathExpr('composer', $path);
            $entries .= "    '{$escapedClass}' => {$relativePath},\n";
        }

        $content = <<<PHP
<?php

// autoload_classmap.php @generated by Mozart

\$vendorDir = dirname(__DIR__);
\$baseDir = {$this->computeBaseDirExpr()};

return array(
{$entries});

PHP;

        $this->files->writeFile(
            $this->config->getDepDirectory() . 'composer/autoload_classmap.php',
            $content
        );
    }

    /**
     * Write the autoload_psr4.php file.
     */
    protected function writeAutoloadPsr4(): void
    {
        $entries = '';
        foreach ($this->psr4Entries as $prefix => $directories) {
            $escapedPrefix = addslashes($prefix);
            $dirEntries = [];
            foreach ($directories as $dir) {
                $dirEntries[] = $this->computeRelativePathExpr('composer', $dir);
            }
            $entries .= "    '{$escapedPrefix}' => array(" . implode(', ', $dirEntries) . "),\n";
        }

        $content = <<<PHP
<?php

// autoload_psr4.php @generated by Mozart

\$vendorDir = dirname(__DIR__);
\$baseDir = {$this->computeBaseDirExpr()};

return array(
{$entries});

PHP;

        $this->files->writeFile(
            $this->config->getDepDirectory() . 'composer/autoload_psr4.php',
            $content
        );
    }

    /**
     * Write the autoload_files.php file.
     */
    protected function writeAutoloadFiles(): void
    {
        $entries = '';
        foreach ($this->filesEntries as $identifier => $path) {
            $relativePath = $this->computeRelativePathExpr('composer', $path);
            $entries .= "    '{$identifier}' => {$relativePath},\n";
        }

        $content = <<<PHP
<?php

// autoload_files.php @generated by Mozart

\$vendorDir = dirname(__DIR__);
\$baseDir = {$this->computeBaseDirExpr()};

return array(
{$entries});

PHP;

        $this->files->writeFile(
            $this->config->getDepDirectory() . 'composer/autoload_files.php',
            $content
        );
    }

    /**
     * Copy ClassLoader.php from the project's vendor/composer/ directory.
     */
    protected function copyClassLoader(): void
    {
        $source = $this->config->getWorkingDir() . 'vendor'
            . DIRECTORY_SEPARATOR . 'composer' . DIRECTORY_SEPARATOR . 'ClassLoader.php';

        if (!file_exists($source)) {
            throw new FileOperationException(
                'Cannot find vendor/composer/ClassLoader.php. '
                . 'Run "composer install" before generating the autoloader.'
            );
        }

        $this->files->copyFile(
            'vendor' . DIRECTORY_SEPARATOR . 'composer' . DIRECTORY_SEPARATOR . 'ClassLoader.php',
            $this->config->getDepDirectory() . 'composer' . DIRECTORY_SEPARATOR . 'ClassLoader.php'
        );
    }

    /**
     * Copy the Composer LICENSE file.
     */
    protected function copyLicense(): void
    {
        $source = 'vendor' . DIRECTORY_SEPARATOR . 'composer' . DIRECTORY_SEPARATOR . 'LICENSE';

        if (!file_exists($this->config->getWorkingDir() . $source)) {
            return;
        }

        $this->files->copyFile(
            $source,
            $this->config->getDepDirectory() . 'composer' . DIRECTORY_SEPARATOR . 'LICENSE'
        );
    }

    /**
     * Compute a relative path from one location to another.
     *
     * @param string $from Directory path to compute from (relative to working dir)
     * @param string $target File or directory path to reach (relative to working dir)
     * @return string Relative path
     */
    public function computeRelativePath(string $from, string $target): string
    {
        $fromParts = array_values(array_filter(explode('/', str_replace(DIRECTORY_SEPARATOR, '/', $from))));
        $targetParts = array_values(array_filter(explode('/', str_replace(DIRECTORY_SEPARATOR, '/', $target))));

        // Find common prefix length
        $commonLength = 0;
        $maxLength = min(count($fromParts), count($targetParts));
        for ($i = 0; $i < $maxLength; $i++) {
            if ($fromParts[$i] !== $targetParts[$i]) {
                break;
            }
            $commonLength++;
        }

        // Build relative path: go up from $from, then down to $target
        $upCount = count($fromParts) - $commonLength;
        $downParts = array_slice($targetParts, $commonLength);

        $parts = array_merge(
            array_fill(0, $upCount, '..'),
            $downParts
        );

        return implode('/', $parts);
    }

    /**
     * Compute a PHP expression for a path relative to a directory.
     *
     * @param string $fromDir Directory within dep_directory (e.g., 'composer')
     * @param string $toPath Target path relative to working directory
     * @return string PHP expression like "$vendorDir . '/path'"
     */
    protected function computeRelativePathExpr(string $fromDir, string $toPath): string
    {
        $depDir = rtrim($this->config->getDepDirectory(), DIRECTORY_SEPARATOR . '/');
        $from = $depDir . '/' . $fromDir;

        $relative = $this->computeRelativePath($from, $toPath);

        // Count leading '..' segments to determine if path goes beyond dep_directory
        $parts = explode('/', $relative);
        $upCount = 0;
        while (isset($parts[$upCount]) && $parts[$upCount] === '..') {
            $upCount++;
        }

        // 'composer' is 1 level deep in dep_directory, so going up >1 goes beyond dep_directory
        if ($upCount > 1) {
            return "\$baseDir . '/" . ltrim($toPath, '/') . "'";
        }

        return "\$vendorDir . '/" . implode('/', array_slice($parts, $upCount)) . "'";
    }

    /**
     * Compute the $baseDir expression for generated files.
     *
     * @return string PHP expression for the project root relative to dep_directory/composer/
     */
    protected function computeBaseDirExpr(): string
    {
        $depDir = rtrim($this->config->getDepDirectory(), DIRECTORY_SEPARATOR . '/');
        $depth = count(array_filter(explode('/', $depDir)));

        // From composer/ inside dep_directory, we need to go up depth+1 levels
        return "dirname(\$vendorDir, {$depth})";
    }

    /**
     * Render the static $files array for autoload_static.php.
     *
     * @param string $depDir Dependency directory (without trailing separator)
     */
    protected function renderStaticFilesArray(string $depDir): string
    {
        $lines = "    public static \$files = array (\n";
        foreach ($this->filesEntries as $identifier => $path) {
            $dirExpr = $this->computeStaticDirExpr($path, $depDir);
            $lines .= "        '{$identifier}' => {$dirExpr},\n";
        }
        $lines .= "    );\n\n";

        return $lines;
    }

    /**
     * Render the static $prefixLengthsPsr4 array.
     */
    protected function renderStaticPrefixLengths(): string
    {
        $lines = "    public static \$prefixLengthsPsr4 = array (\n";
        foreach (array_keys($this->psr4Entries) as $prefix) {
            $firstChar = $prefix[0];
            $escapedPrefix = addslashes($prefix);
            $length = strlen($prefix);
            $lines .= "        '{$firstChar}' =>\n";
            $lines .= "        array (\n";
            $lines .= "            '{$escapedPrefix}' => {$length},\n";
            $lines .= "        ),\n";
        }
        $lines .= "    );\n\n";

        return $lines;
    }

    /**
     * Render the static $prefixDirsPsr4 array.
     *
     * @param string $depDir The dependency directory path (without trailing separator)
     */
    protected function renderStaticPrefixDirs(string $depDir): string
    {
        $lines = "    public static \$prefixDirsPsr4 = array (\n";
        foreach ($this->psr4Entries as $prefix => $directories) {
            $escapedPrefix = addslashes($prefix);
            $lines .= "        '{$escapedPrefix}' =>\n";
            $lines .= "        array (\n";
            foreach ($directories as $dir) {
                $dirExpr = $this->computeStaticDirExpr($dir, $depDir);
                $lines .= "            0 => {$dirExpr},\n";
            }
            $lines .= "        ),\n";
        }
        $lines .= "    );\n\n";

        return $lines;
    }

    /**
     * Render the static $classMap array.
     *
     * @param string $depDir The dependency directory path (without trailing separator)
     */
    protected function renderStaticClassmap(string $depDir): string
    {
        $lines = "    public static \$classMap = array (\n";
        foreach ($this->classmapEntries as $class => $path) {
            $escapedClass = addslashes($class);
            $dirExpr = $this->computeStaticDirExpr($path, $depDir);
            $lines .= "        '{$escapedClass}' => {$dirExpr},\n";
        }
        $lines .= "    );\n\n";

        return $lines;
    }

    /**
     * Compute a __DIR__-relative expression for autoload_static.php.
     *
     * @param string $path Path relative to working directory
     * @param string $depDir Dependency directory (without trailing separator)
     * @return string PHP expression like "__DIR__ . '/../path'"
     */
    protected function computeStaticDirExpr(string $path, string $depDir): string
    {
        // __DIR__ is dep_directory/composer/
        $from = $depDir . '/composer';
        $relative = $this->computeRelativePath($from, $path);

        return "__DIR__ . '/" . $relative . "'";
    }

    /**
     * Render the initializer closure body for autoload_static.php.
     */
    protected function renderStaticInitializer(): string
    {
        $hash = $this->hash;
        $lines = '';

        if (!empty($this->psr4Entries)) {
            $lines .= "            \$loader->prefixLengthsPsr4"
                . " = MozartStaticInit{$hash}::\$prefixLengthsPsr4;\n";
            $lines .= "            \$loader->prefixDirsPsr4"
                . " = MozartStaticInit{$hash}::\$prefixDirsPsr4;\n";
        }

        if (!empty($this->classmapEntries)) {
            $lines .= "            \$loader->classMap"
                . " = MozartStaticInit{$hash}::\$classMap;\n";
        }

        return rtrim($lines, "\n");
    }

    /**
     * Get the generated hash (for testing).
     */
    public function getHash(): string
    {
        return $this->hash;
    }

    /**
     * Get the PSR-4 entries (for testing).
     *
     * @return array<string, array<string>>
     */
    public function getPsr4Entries(): array
    {
        return $this->psr4Entries;
    }

    /**
     * Get the classmap entries (for testing).
     *
     * @return array<string, string>
     */
    public function getClassmapEntries(): array
    {
        return $this->classmapEntries;
    }

    /**
     * Get the files entries (for testing).
     *
     * @return array<string, string>
     */
    public function getFilesEntries(): array
    {
        return $this->filesEntries;
    }
}
