<?php

namespace CoenJacobs\Mozart\Autoload;

use CoenJacobs\Mozart\FilesHandler;

/**
 * Writes Composer-compatible autoloader PHP files for prefixed dependencies.
 */
class AutoloaderFileWriter
{
    protected FilesHandler $files;
    protected string $depDirectory;
    protected string $hash;
    protected PathHelper $pathHelper;

    public function __construct(FilesHandler $files, string $depDirectory, string $hash)
    {
        $this->files = $files;
        $this->depDirectory = $depDirectory;
        $this->hash = $hash;
        $this->pathHelper = new PathHelper();
    }

    /**
     * Write all autoloader files.
     *
     * @param array<string, array<string>> $psr4 PSR-4 prefix => directories
     * @param array<string, string> $classmap FQCN => file path
     * @param array<string, string> $files hash => file path
     */
    public function write(array $psr4, array $classmap, array $files): void
    {
        $this->writeAutoloadPhp();
        $this->writeAutoloadReal($files);
        $this->writeAutoloadStatic($psr4, $classmap, $files);

        $classmapEntries = '';
        foreach ($classmap as $class => $path) {
            $escapedClass = addslashes($class);
            $relativePath = $this->formatPathExpr('composer', $path);
            $classmapEntries .= "    '{$escapedClass}' => {$relativePath},\n";
        }
        $this->writeArrayFile('autoload_classmap.php', $classmapEntries);

        $psr4Entries = '';
        foreach ($psr4 as $prefix => $directories) {
            $escapedPrefix = addslashes($prefix);
            $dirEntries = [];
            foreach ($directories as $dir) {
                $dirEntries[] = $this->formatPathExpr('composer', $dir);
            }
            $psr4Entries .= "    '{$escapedPrefix}' => array(" . implode(', ', $dirEntries) . "),\n";
        }
        $this->writeArrayFile('autoload_psr4.php', $psr4Entries);

        if (!empty($files)) {
            $filesEntries = '';
            foreach ($files as $identifier => $path) {
                $relativePath = $this->formatPathExpr('composer', $path);
                $filesEntries .= "    '{$identifier}' => {$relativePath},\n";
            }
            $this->writeArrayFile('autoload_files.php', $filesEntries);
        }
    }

    /**
     * Write the autoload.php entry point.
     */
    protected function writeAutoloadPhp(): void
    {
        $content = <<<PHP
<?php

// autoload.php @generated by Mozart

require_once __DIR__ . '/composer/autoload_real.php';

return MozartAutoloaderInit{$this->hash}::getLoader();

PHP;

        $this->files->writeFile(
            $this->depDirectory . 'autoload.php',
            $content
        );
    }

    /**
     * Write the autoload_real.php bootstrap file.
     *
     * @param array<string, string> $files hash => file path
     */
    protected function writeAutoloadReal(array $files): void
    {
        $hash = $this->hash;
        $filesBlock = '';

        if (!empty($files)) {
            $filesBlock = <<<'FILESBLOCK'

        $filesToLoad = \Composer\Autoload\MozartStaticInit{HASH}::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }
FILESBLOCK;
            $filesBlock = str_replace('{HASH}', $hash, $filesBlock);
        }

        $content = <<<PHP
<?php

// autoload_real.php @generated by Mozart

class MozartAutoloaderInit{$hash}
{
    private static \$loader;

    public static function loadClassLoader(\$class)
    {
        if ('Composer\\Autoload\\ClassLoader' === \$class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \\Composer\\Autoload\\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::\$loader) {
            return self::\$loader;
        }

        spl_autoload_register(array('MozartAutoloaderInit{$hash}', 'loadClassLoader'), true, true);
        self::\$loader = \$loader = new \\Composer\\Autoload\\ClassLoader(\\dirname(__DIR__));
        spl_autoload_unregister(array('MozartAutoloaderInit{$hash}', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\\Composer\\Autoload\\MozartStaticInit{$hash}::getInitializer(\$loader));

        \$loader->register(true);
{$filesBlock}

        return \$loader;
    }
}

PHP;

        $this->files->writeFile(
            $this->depDirectory . 'composer/autoload_real.php',
            $content
        );
    }

    /**
     * Write the autoload_static.php file with static arrays for OPcache.
     *
     * @param array<string, array<string>> $psr4 PSR-4 prefix => directories
     * @param array<string, string> $classmap FQCN => file path
     * @param array<string, string> $files hash => file path
     */
    protected function writeAutoloadStatic(array $psr4, array $classmap, array $files): void
    {
        $hash = $this->hash;
        $depDir = rtrim($this->pathHelper->normalize($this->depDirectory), '/');

        // Build files array
        $filesArray = '';
        if (!empty($files)) {
            $filesArray = "    public static \$files = array (\n";
            foreach ($files as $identifier => $path) {
                $dirExpr = "__DIR__ . '/" . $this->computeRelativePath($depDir . '/composer', $path) . "'";
                $filesArray .= "        '{$identifier}' => {$dirExpr},\n";
            }
            $filesArray .= "    );\n\n";
        }

        // Build PSR-4 arrays
        $prefixLengths = "    public static \$prefixLengthsPsr4 = array (\n";
        foreach (array_keys($psr4) as $prefix) {
            $firstChar = $prefix[0];
            $escapedPrefix = addslashes($prefix);
            $length = strlen($prefix);
            $prefixLengths .= "        '{$firstChar}' =>\n";
            $prefixLengths .= "        array (\n";
            $prefixLengths .= "            '{$escapedPrefix}' => {$length},\n";
            $prefixLengths .= "        ),\n";
        }
        $prefixLengths .= "    );\n\n";

        $prefixDirs = "    public static \$prefixDirsPsr4 = array (\n";
        foreach ($psr4 as $prefix => $directories) {
            $escapedPrefix = addslashes($prefix);
            $prefixDirs .= "        '{$escapedPrefix}' =>\n";
            $prefixDirs .= "        array (\n";
            foreach ($directories as $dir) {
                $dirExpr = "__DIR__ . '/" . $this->computeRelativePath($depDir . '/composer', $dir) . "'";
                $prefixDirs .= "            0 => {$dirExpr},\n";
            }
            $prefixDirs .= "        ),\n";
        }
        $prefixDirs .= "    );\n\n";

        // Build classmap array
        $classmapArray = "    public static \$classMap = array (\n";
        foreach ($classmap as $class => $path) {
            $escapedClass = addslashes($class);
            $dirExpr = "__DIR__ . '/" . $this->computeRelativePath($depDir . '/composer', $path) . "'";
            $classmapArray .= "        '{$escapedClass}' => {$dirExpr},\n";
        }
        $classmapArray .= "    );\n\n";

        // Build initializer body
        $initLines = '';
        if (!empty($psr4)) {
            $initLines .= "            \$loader->prefixLengthsPsr4"
                . " = MozartStaticInit{$hash}::\$prefixLengthsPsr4;\n";
            $initLines .= "            \$loader->prefixDirsPsr4"
                . " = MozartStaticInit{$hash}::\$prefixDirsPsr4;\n";
        }
        if (!empty($classmap)) {
            $initLines .= "            \$loader->classMap"
                . " = MozartStaticInit{$hash}::\$classMap;\n";
        }
        $initLines = rtrim($initLines, "\n");

        $content = <<<PHP
<?php

// autoload_static.php @generated by Mozart

namespace Composer\Autoload;

class MozartStaticInit{$hash}
{
{$filesArray}{$prefixLengths}{$prefixDirs}{$classmapArray}
    public static function getInitializer(ClassLoader \$loader)
    {
        return \\Closure::bind(function () use (\$loader) {
{$initLines}
        }, null, ClassLoader::class);
    }
}

PHP;

        $this->files->writeFile(
            $this->depDirectory . 'composer/autoload_static.php',
            $content
        );
    }

    /**
     * Write an array-returning autoloader file (classmap, psr4, or files).
     *
     * @param string $filename The filename within the composer/ directory
     * @param string $entries Pre-formatted array entries
     */
    protected function writeArrayFile(string $filename, string $entries): void
    {
        $this->files->writeFile(
            $this->depDirectory . 'composer/' . $filename,
            $this->buildArrayFileContent($filename, $entries, $this->buildBaseDirExpr())
        );
    }

    /**
     * Compute a relative path from one location to another.
     *
     * @param string $from Directory path to compute from (relative to working dir)
     * @param string $target File or directory path to reach (relative to working dir)
     * @return string Relative path
     */
    public function computeRelativePath(string $from, string $target): string
    {
        return $this->pathHelper->relativePath($from, $target);
    }

    /**
     * Convert a path to a PHP expression using $vendorDir or $baseDir.
     *
     * @param string $fromDir Directory within dep_directory (e.g., 'composer')
     * @param string $toPath Target path relative to working directory
     * @return string PHP expression like "$vendorDir . '/path'"
     */
    protected function formatPathExpr(string $fromDir, string $toPath): string
    {
        $depDir = rtrim($this->pathHelper->normalize($this->depDirectory), '/');
        $from = $depDir . '/' . $fromDir;
        $normalizedPath = $this->pathHelper->normalize($toPath);

        $relative = $this->computeRelativePath($from, $normalizedPath);

        // Count leading '..' segments to determine if path goes beyond dep_directory
        $parts = explode('/', $relative);
        $upCount = 0;
        while (isset($parts[$upCount]) && $parts[$upCount] === '..') {
            $upCount++;
        }

        // 'composer' is 1 level deep in dep_directory, so going up >1 goes beyond dep_directory
        if ($upCount > 1) {
            return "\$baseDir . '/" . ltrim($normalizedPath, '/') . "'";
        }

        return "\$vendorDir . '/" . implode('/', array_slice($parts, $upCount)) . "'";
    }

    /**
     * Build the PHP content for an array-returning autoloader file.
     */
    protected function buildArrayFileContent(string $filename, string $entries, string $baseDirExpr): string
    {
        return <<<PHP
<?php

// {$filename} @generated by Mozart

\$vendorDir = dirname(__DIR__);
\$baseDir = {$baseDirExpr};

return array(
{$entries});

PHP;
    }

    /**
     * Build the base-dir expression used by generated array files.
     */
    protected function buildBaseDirExpr(): string
    {
        $depDir = rtrim($this->pathHelper->normalize($this->depDirectory), '/');
        $depth = $this->pathHelper->countSegments($depDir);

        return "dirname(\$vendorDir, {$depth})";
    }
}
