name: Run PHP CodeSniffer

# Run PHPCBF to fix changes then commit the change and annotates with remaining PHPCS errors.
#
# NB: Pull requests from forks do not have access to repository secrets so cannot commit changes.
#
# @author BrianHenryIE

on:
  push:
    branches:
      - master

jobs:
  php-codesniffer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install PHP
        uses: shivammathur/setup-php@1.3.7
        with:
          php-version: '7.4'
          tools: composer, cs2pr

      - name: Debugging
        run: |
          php --version
          php -m
          composer --version

      - name: Install dependencies
        run: composer install --prefer-dist --no-suggest --no-progress

      - name: PHPCBF
        continue-on-error: true
        run: vendor/bin/phpcbf

      - name: Commit PHPCBF changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: "PHPCBF"

      - name: Run PHPCS to add annotations to the commit
        continue-on-error: true
        run: vendor/bin/phpcs --report=checkstyle | cs2pr
